[Tool] debug

diff --git a/.github/workflows/approve-checker.yml b/.github/workflows/approve-checker.yml
--- a/.github/workflows/approve-checker.yml
+++ b/.github/workflows/approve-checker.yml
@@ -63,7 +63,7 @@ jobs:
     needs: info
     runs-on: ubuntu-latest
     if: contains(needs.info.outputs.LABELS, 'META-REVIEW')
-    continue-on-error: false
+
     env:
       PR_NUMBER: ${{ needs.info.outputs.PR_NUMBER }}
       REPO: ${{ github.repository }}
@@ -86,4 +86,5 @@ jobs:
             done
           done
           
-          echo "::error title=test::Lack of META-TEAM members' approval"
+          echo "::error::Lack of META-TEAM members' approval"
+          exit 1
