[Doc] Vale rule to prevent HTML comments in docs outside of code blocks (#71627)
Signed-off-by: DanRoscigno <dan@roscigno.com>
(cherry picked from commit c1b01f13640f42ea3b69bbd23598c004b7ceb943)

# Conflicts:
#	.github/workflows/ci-doc-checker.yml

diff --git a/.github/workflows/ci-doc-checker.yml b/.github/workflows/ci-doc-checker.yml
--- a/.github/workflows/ci-doc-checker.yml
+++ b/.github/workflows/ci-doc-checker.yml
@@ -118,6 +118,50 @@ jobs:
           globs: ${{ steps.changed-files.outputs.all_changed_files }}
           separator: ","
 
+<<<<<<< HEAD
+=======
+  docusaurus-build:
+    runs-on: ubuntu-latest
+    needs: markdownlint # Only runs if markdownlint passes!
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+    steps:
+
+
+      # 1. Replicate the branch info and complex checkout logic
+      - name: clean
+        run: |
+          rm -rf ${{ github.workspace }}
+          mkdir -p ${{ github.workspace }}
+          
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Checkout PR
+        run: |
+          BRANCH=${{steps.branch.outputs.branch}}
+          git config --global user.name "docs-automation[bot]"
+          git config --global user.email "docs-automation[bot]@starrocks.io"
+          git checkout $BRANCH
+          git pull
+          BRANCH_NAME="${BRANCH}-${PR_NUMBER}"
+          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME}
+          git checkout $BRANCH_NAME
+          git checkout -b merge_pr
+          git merge --squash --no-edit ${BRANCH} || (echo "::error::Merge conflict, please check." && exit -1)
+
+      # 2. Replicate the Node.js setup
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 24
+
+>>>>>>> c1b01f1364 ([Doc] Vale rule to prevent HTML comments in docs outside of code blocks (#71627))
       - name: docusaurus-mdx-checker
         if: always()
         run: |
@@ -134,7 +178,7 @@ jobs:
 
       - name: Docusaurus build
         env:
-          NODE_OPTIONS: --max-old-space-size=8192
+          NODE_OPTIONS: --max-old-space-size=9216
           DISABLE_VERSIONING: true
           DOCUSAURUS_IGNORE_SSG_WARNINGS: true
         working-directory: ./docs/docusaurus
