[Tool] SQL-Tester add param: cloud/native (#41136)
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>
(cherry picked from commit dc6e8605c81ecfe24c0731920604f416e64c481e)

# Conflicts:
#	.github/workflows/ci-pipeline.yml
#	.github/workflows/inspection-pipeline.yml

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -317,6 +317,59 @@ jobs:
           git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
           git checkout $BRANCH_NAME;
           git checkout -b merge_pr;
+<<<<<<< HEAD
+=======
+          git merge --squash --no-edit ${BRANCH} || (echo "::error::Merge conflict, please check." && exit -1);
+
+      - name: Copy checkstyle files
+        if: needs.fe-checker.outputs.java_filter == 'true'
+        run: |
+          cp fe/checkstyle* .
+
+      - name: Run java checkstyle
+        if: needs.fe-checker.outputs.java_filter == 'true'
+        uses: dbelyaev/action-checkstyle@v1.5.6
+        with:
+          workdir: "./fe"
+          checkstyle_config: checkstyle.xml
+          reporter: 'github-pr-check'
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          fail_on_error: true
+          level: error
+
+  sonarcloud-fe-checker:
+    runs-on: ubuntu-latest
+    needs: fe-checker
+    if: needs.fe-checker.outputs.src_filter == 'true' && github.repository == 'StarRocks/starrocks'
+    name: FE Sonarcloud Check
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+      CODE_PATH: ${{ github.workspace }}
+      BRANCH: ${{ github.base_ref }}
+      GH_TOKEN: ${{ github.token }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+      - name: Checkout PR
+        run: |
+          BRANCH=${{steps.branch.outputs.branch}}
+          git config --global user.name "wanpengfei-git";
+          git config --global user.email "wanpengfei91@163.com";
+          git checkout $BRANCH;
+          git pull;
+          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
+          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
+          git checkout $BRANCH_NAME;
+          git checkout -b merge_pr;
+>>>>>>> dc6e8605c8 ([Tool] SQL-Tester add param: cloud/native (#41136))
           git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
 
       - name: Copy checkstyle files
@@ -597,7 +650,7 @@ jobs:
       CLUSTER_NAME: ci-admit
       FE_NODE: ${{ needs.deploy.outputs.fe }}
       BE_NODE: ${{ needs.deploy.outputs.be }}
-      BASE_VERSION: ${{needs.build.outputs.base_version}}
+      BASE_VERSION: ${{ needs.build.outputs.base_version }}
     outputs:
       MYSQL_ECI_ID: ${{ steps.run_case.outputs.MYSQL_ECI_ID }}
     steps:
@@ -661,8 +714,13 @@ jobs:
   admit:
     runs-on: [self-hosted, normal]
     name: ADMIT TEST
+<<<<<<< HEAD
     needs: [ deploy, SQL-Tester ]
     if: always() && needs.deploy.result == 'success' && needs.SQL-Tester.result == 'success'
+=======
+    needs: [ deploy, restart-fe, restart-be ]
+    if: always() && needs.restart-fe.result == 'success' && needs.restart-be.result == 'success' && needs.deploy.outputs.is_self_build == 'true'
+>>>>>>> dc6e8605c8 ([Tool] SQL-Tester add param: cloud/native (#41136))
     timeout-minutes: 40
     env:
       PR_NUMBER: ${{ github.event.number }}
