fix
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -98,7 +98,6 @@ jobs:
           cd ci-tool
           # TODO: check fork repo
           ./scripts/check-testcase.sh
-          echo "TEST_PR=9909" >> $GITHUB_OUTPUT
 
       - name: Check Feature Issue
         id: check_issue
@@ -159,7 +158,7 @@ jobs:
           elif [[ "${status}" == "bugfix-only" ]] && [[ "${PR_TITLE}" == *"[Feature]"* || "${PR_TITLE}" == *"[Enhancement]"* ]]; then
             comment="⚠️ Branch in bugfix-only state, [Feature] or [Enhancement] PRs are not allowed!"
           elif [[ "${status}" == "code-freeze" ]] && [[ "${PR_TITLE}" != *"[Bugfix]"* || "${PR_TITLE}" != *"CVE"* ]]; then
-            comment="⚠️ Branch in code-freeze state, only PRs that fix CVE CVE are allowed!"
+            comment="⚠️ Branch in code-freeze state, only PRs that fix CVE are allowed!"
           else
             exit 0
           fi
@@ -1024,7 +1023,6 @@ jobs:
       - name: Restart FE (${{needs.deploy.outputs.fe}})
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
           ./bin/restart-fe.sh --pr ${PR_NUMBER} --branch ${{ github.base_ref }} --build Release --repository ${{ github.repository }}
 
       - name: Clean ENV
@@ -1052,7 +1050,6 @@ jobs:
       - name: Restart BE (${{needs.deploy.outputs.be_list}})
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
           [[ "${{ needs.deploy.outputs.is_self_build }}" != "true" ]] && gcov_cmd="--skip-gcov"
           ./bin/system-cov-be.sh \
             --pr ${PR_NUMBER} \
@@ -1097,18 +1094,17 @@ jobs:
           BRANCH: ${{ steps.branch.outputs.branch }}
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
 
           cd ${{ github.workspace }}/..
           rm -rf ./StarRocksTest && cp -rf /var/lib/StarRocksTest ./StarRocksTest && cd ./StarRocksTest && git pull >/dev/null
+
           if [[ "${TEST_PR}" != "" ]]; then
             echo "Test pr: ${TEST_PR}..."
-            git checkout combine-py-sql
             BRANCH_NAME="${BRANCH}-${PR_NUMBER}"
             git fetch origin pull/${TEST_PR}/head:${BRANCH_NAME}
             git checkout $BRANCH_NAME
             git checkout -b merge_pr
-            git merge --squash --no-edit combine-py-sql || (echo "::error::Merge conflict, please check." && exit -1);
+            git merge --squash --no-edit master || (echo "::error::Merge conflict, please check." && exit -1);
           fi
           mv ${{ github.workspace }}/../StarRocksTest ${{ github.workspace }}/StarRocksTest
 
@@ -1155,7 +1151,6 @@ jobs:
       - name: Restart FE (${{needs.deploy.outputs.be_list}})
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
           ./bin/restart-fe.sh \
             --pr ${PR_NUMBER} \
             --branch ${{ github.base_ref }} \
@@ -1189,7 +1184,6 @@ jobs:
       - name: Restart BE (${{needs.deploy.outputs.be_list}})
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
           [[ "${{ needs.deploy.outputs.is_self_build }}" != "true" ]] && gcov_cmd="--skip-gcov"
           ./bin/system-cov-be.sh \
             --pr ${PR_NUMBER} \
@@ -1235,7 +1229,6 @@ jobs:
         id: backup
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          git checkout gen_cov_split
           ./bin/backup_log_cores.sh \
             --branch $BRANCH \
             --pr $PR_NUMBER \
