Revert "[Tool] Parallel `BE UT` & `BUILD` to optimize CI time"
This reverts commit c61fdbc90ecc0f33f6cf7cd64a32a82108c650f6.

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -37,221 +37,10 @@ jobs:
         run: |
           echo "pass=true" >> $GITHUB_OUTPUT
 
-  be-checker:
-    runs-on: ubuntu-latest
-    needs: sync-checker
-    name: 2. BE FILTER
-    if: needs.sync-checker.outputs.PASS == 'true'
-    outputs:
-      output1: ${{ steps.be-changes-info.outputs.be }}
-      output2: ${{ steps.be-changes-info.outputs.thirdparty }}
-    steps:
-      - uses: dorny/paths-filter@v2
-        id: changes
-        with:
-          filters: |
-            be:
-            - 'be/**'
-            - 'gensrc/**'
-            - 'run-be-ut.sh'
-            - 'build.sh'
-            - 'thirdparty/**'
-            - 'docker/dockerfiles/dev-env/dev-env.Dockerfile'
-            thirdparty:
-            - 'thirdparty/**'
-            - 'docker/dockerfiles/dev-env/dev-env.Dockerfile'
-
-      - name: BE CHECK INFO
-        id: be-changes-info
-        run: |
-          echo "be=${{ steps.changes.outputs.be }}" >> $GITHUB_OUTPUT
-          echo "thirdparty=${{ steps.changes.outputs.thirdparty }}" >> $GITHUB_OUTPUT
-
-  clang-format:
-    runs-on: [self-hosted, light]
-    needs: be-checker
-    name: Clang-Format
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-    if: ${{ needs.be-checker.outputs.output1 == 'true' }}
-    steps:
-      - name: clean
-        run: |
-          rm -rf ${{ github.workspace }}
-          mkdir -p ${{ github.workspace }}
-
-      - name: Checkout Code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: BRANCH INFO
-        id: branch
-        run: |
-          echo ${{github.base_ref}}
-          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-
-      - name: Checkout PR
-        run: |
-          BRANCH=${{steps.branch.outputs.branch}}
-          git config --global user.name "wanpengfei-git";
-          git config --global user.email "wanpengfei91@163.com";
-          git checkout $BRANCH;
-          git pull;
-          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
-          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
-          git checkout $BRANCH_NAME;
-          git checkout -b merge_pr;
-          git merge --squash --no-edit ${BRANCH} || (echo "::error::Merge conflict, please check." && exit -1);
-
-      - name: Run Clang-Format
-        run: |
-          export PATH=/var/lib/llvm/bin:$PATH
-          bash build-support/check-format.sh
-
-      - name: Clean ENV
-        if: always()
-        run: |
-          rm -rf ${{ github.workspace }}/*
-
-  thirdparty-update:
-    runs-on: [self-hosted, normal]
-    needs: [ be-checker, clang-format ]
-    name: Thirdparty Update
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-      BRANCH: ${{ github.base_ref }}
-      REPO: ${{ github.repository }}
-    outputs:
-      ip: ${{ steps.update-image.outputs.ip }}
-      instance_id: ${{ steps.update-image.outputs.instance_id }}
-      image_cache_id: ${{ steps.update-image.outputs.image_cache_id }}
-    steps:
-      - name: clean
-        run: |
-          rm -rf ${{ github.workspace }}
-          mkdir -p ${{ github.workspace }}
-
-      - name: Checkout Code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Update Image
-        id: update-image
-        run: |
-          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
-              rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-              ./bin/run-pr-update-image.sh
-          fi
-
-      - name: Clean ENV
-        if: always()
-        run: |
-          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
-              cd ci-tool && source lib/init.sh
-              ./bin/elastic-cluster.sh --delete
-          fi
-          rm -rf ${{ github.workspace }}/*
-
-  be-ut:
-    runs-on: [self-hosted, normal]
-    needs: [ be-checker, thirdparty-update ]
-    timeout-minutes: 180
-    name: BE UT
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-      BRANCH: ${{ github.base_ref }}
-    steps:
-      - name: BRANCH INFO
-        id: branch
-        run: |
-          echo ${{github.base_ref}}
-          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-
-      - name: UPDATE ECI & RUN UT
-        id: run_ut
-        shell: bash
-        timeout-minutes: 180
-        run: |
-          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
-              export image_cache_id=${{ needs.thirdparty-update.outputs.image_cache_id }}
-              export image_tag=$BRANCH-$PR_NUMBER
-          fi
-          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module be --repository ${{ github.repository }} --with-gcov
-
-      - name: clean ECI
-        if: always()
-        run: |
-          echo ${{ steps.run_ut.outputs.ECI_ID }}
-          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
-
-      - name: Upload Log
-        uses: actions/upload-artifact@v3
-        if: always() && steps.run_ut.outcome == 'failure'
-        with:
-          name: BE UT LOG
-          path: ${{ steps.run_ut.outputs.BE_LOG }}
-          retention-days: 1
-
-      - name: Clean ENV
-        if: always()
-        run: |
-          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
-          rm -f ${{ steps.run_ut.outputs.RES_LOG }}
-          rm -rf ${{ steps.run_ut.outputs.BE_LOG }}
-          rm -rf ${{ github.workspace }}/*
-
-  clang-tidy:
-    runs-on: [self-hosted, normal]
-    needs: [ be-checker, thirdparty-update ]
-    timeout-minutes: 90
-    name: Clang-Tidy
-    env:
-      PR_NUMBER: ${{ github.event.number }}
-      BRANCH: ${{ github.base_ref }}
-    steps:
-      - name: clean
-        run: |
-          rm -rf ${{ github.workspace }}
-          mkdir -p ${{ github.workspace }}
-
-      - name: BRANCH INFO
-        id: branch
-        run: |
-          echo ${{github.base_ref}}
-          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-
-      - name: UPDATE ECI & RUN Clang Tidy
-        id: run_clang_tidy
-        shell: bash
-        timeout-minutes: 60
-        run: |
-          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
-          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
-              export image_cache_id=${{ needs.thirdparty-update.outputs.image_cache_id }}
-              export image_tag=$BRANCH-$PR_NUMBER
-          fi
-          ./bin/elastic-build.sh --pr ${PR_NUMBER} --repository ${{ github.repository }} --be --clang-tidy
-
-      - name: clean ECI
-        if: always()
-        run: |
-          echo ${{ steps.run_clang_tidy.outputs.ECI_ID }}
-          eci rm ${{ steps.run_clang_tidy.outputs.ECI_ID }}
-
-      - name: Clean ENV
-        if: always()
-        run: |
-          rm -f ${{ steps.run_clang_tidy.outputs.RES_FILE }}
-          rm -f ${{ steps.run_clang_tidy.outputs.RES_LOG }}
-          rm -rf ${{ github.workspace }}/*
-
   fe-checker:
     runs-on: ubuntu-latest
     needs: sync-checker
-    name: 1. FE FILTER
+    name: FE FILTER
     if: needs.sync-checker.outputs.PASS == 'true'
     outputs:
       output1: ${{ steps.fe-changes-info.outputs.fe }}
@@ -473,10 +262,222 @@ jobs:
           rm -rf ${{ steps.run_ut.outputs.COV_DIR }}
           rm -rf ${{ github.workspace }}/*
 
+  be-checker:
+    runs-on: ubuntu-latest
+    needs: sync-checker
+    name: BE FILTER
+    if: needs.sync-checker.outputs.PASS == 'true'
+    outputs:
+      output1: ${{ steps.be-changes-info.outputs.be }}
+      output2: ${{ steps.be-changes-info.outputs.thirdparty }}
+    steps:
+      - uses: dorny/paths-filter@v2
+        id: changes
+        with:
+          filters: |
+            be:
+            - 'be/**'
+            - 'gensrc/**'
+            - 'run-be-ut.sh'
+            - 'build.sh'
+            - 'thirdparty/**'
+            - 'docker/dockerfiles/dev-env/dev-env.Dockerfile'
+            thirdparty:
+            - 'thirdparty/**'
+            - 'docker/dockerfiles/dev-env/dev-env.Dockerfile'
+
+      - name: BE CHECK INFO
+        id: be-changes-info
+        run: |
+          echo "be=${{ steps.changes.outputs.be }}" >> $GITHUB_OUTPUT
+          echo "thirdparty=${{ steps.changes.outputs.thirdparty }}" >> $GITHUB_OUTPUT
+
+  clang-format:
+    runs-on: [self-hosted, light]
+    needs: be-checker
+    name: Clang-Format
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+    if: ${{ needs.be-checker.outputs.output1 == 'true' }}
+    steps:
+      - name: clean
+        run: |
+          rm -rf ${{ github.workspace }}
+          mkdir -p ${{ github.workspace }}
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+      - name: Checkout PR
+        run: |
+          BRANCH=${{steps.branch.outputs.branch}}
+          git config --global user.name "wanpengfei-git";
+          git config --global user.email "wanpengfei91@163.com";
+          git checkout $BRANCH;
+          git pull;
+          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
+          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
+          git checkout $BRANCH_NAME;
+          git checkout -b merge_pr;
+          git merge --squash --no-edit ${BRANCH} || (echo "::error::Merge conflict, please check." && exit -1);
+
+      - name: Run Clang-Format
+        run: |
+          export PATH=/var/lib/llvm/bin:$PATH
+          bash build-support/check-format.sh
+
+      - name: Clean ENV
+        if: always()
+        run: |
+          rm -rf ${{ github.workspace }}/*
+
+  thirdparty-update:
+    runs-on: [self-hosted, normal]
+    needs: [ be-checker, clang-format ]
+    name: Thirdparty Update
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+      BRANCH: ${{ github.base_ref }}
+      REPO: ${{ github.repository }}
+    outputs:
+      ip: ${{ steps.update-image.outputs.ip }}
+      instance_id: ${{ steps.update-image.outputs.instance_id }}
+      image_cache_id: ${{ steps.update-image.outputs.image_cache_id }}
+    steps:
+      - name: clean
+        run: |
+          rm -rf ${{ github.workspace }}
+          mkdir -p ${{ github.workspace }}
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Update Image
+        id: update-image
+        run: |
+          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
+              rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
+              ./bin/run-pr-update-image.sh
+          fi
+
+      - name: Clean ENV
+        if: always()
+        run: |
+          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
+              cd ci-tool && source lib/init.sh
+              ./bin/elastic-cluster.sh --delete
+          fi
+          rm -rf ${{ github.workspace }}/*
+
+  clang-tidy:
+    runs-on: [self-hosted, normal]
+    needs: [ be-checker, thirdparty-update ]
+    timeout-minutes: 90
+    name: Clang-Tidy
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+      BRANCH: ${{ github.base_ref }}
+    steps:
+      - name: clean
+        run: |
+          rm -rf ${{ github.workspace }}
+          mkdir -p ${{ github.workspace }}
+
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+      - name: UPDATE ECI & RUN Clang Tidy
+        id: run_clang_tidy
+        shell: bash
+        timeout-minutes: 60
+        run: |
+          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
+          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
+              export image_cache_id=${{ needs.thirdparty-update.outputs.image_cache_id }}
+              export image_tag=$BRANCH-$PR_NUMBER
+          fi
+          ./bin/elastic-build.sh --pr ${PR_NUMBER} --repository ${{ github.repository }} --be --clang-tidy
+
+      - name: clean ECI
+        if: always()
+        run: |
+          echo ${{ steps.run_clang_tidy.outputs.ECI_ID }}
+          eci rm ${{ steps.run_clang_tidy.outputs.ECI_ID }}
+
+      - name: Clean ENV
+        if: always()
+        run: |
+          rm -f ${{ steps.run_clang_tidy.outputs.RES_FILE }}
+          rm -f ${{ steps.run_clang_tidy.outputs.RES_LOG }}
+          rm -rf ${{ github.workspace }}/*
+
+  be-ut:
+    runs-on: [self-hosted, normal]
+    needs: [ be-checker, thirdparty-update ]
+    timeout-minutes: 180
+    name: BE UT
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+      BRANCH: ${{ github.base_ref }}
+    steps:
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+      - name: UPDATE ECI & RUN UT
+        id: run_ut
+        shell: bash
+        timeout-minutes: 180
+        run: |
+          rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
+          if [[ "${{ needs.be-checker.outputs.output2 }}" == 'true' ]]; then
+              export image_cache_id=${{ needs.thirdparty-update.outputs.image_cache_id }}
+              export image_tag=$BRANCH-$PR_NUMBER
+          fi
+          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module be --repository ${{ github.repository }} --with-gcov
+
+      - name: clean ECI
+        if: always()
+        run: |
+          echo ${{ steps.run_ut.outputs.ECI_ID }}
+          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
+
+      - name: Upload Log
+        uses: actions/upload-artifact@v3
+        if: always() && steps.run_ut.outcome == 'failure'
+        with:
+          name: BE UT LOG
+          path: ${{ steps.run_ut.outputs.BE_LOG }}
+          retention-days: 1
+
+      - name: Clean ENV
+        if: always()
+        run: |
+          rm -f ${{ steps.run_ut.outputs.RES_FILE }}
+          rm -f ${{ steps.run_ut.outputs.RES_LOG }}
+          rm -rf ${{ steps.run_ut.outputs.BE_LOG }}
+          rm -rf ${{ github.workspace }}/*
+
+
   test-checker:
     runs-on: ubuntu-latest
     needs: sync-checker
-    name: 3. TEST FILTER
+    name: TEST FILTER
     if: needs.sync-checker.outputs.PASS == 'true'
     outputs:
       output1: ${{ steps.test-changes-info.outputs.test }}
