[Tool] Support Ubuntu in pipeline (#42718)
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>

(cherry picked from commit a6fe5d55aeb82d47d4ecf0f59fa44cd1e7661996)
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>

diff --git a/.github/workflows/inspection-pipeline.yml b/.github/workflows/inspection-pipeline.yml
--- a/.github/workflows/inspection-pipeline.yml
+++ b/.github/workflows/inspection-pipeline.yml
@@ -5,7 +5,7 @@ on:
     - cron: "30 0 * * 1-5"
     - cron: "30 4 * * 1-5"
     - cron: "30 9 * * 1-5"
-    - cron: "0 11 * * 1-5"
+    - cron: "0 10 * * 1-5"
   workflow_dispatch:
     inputs:
       BRANCH:
@@ -36,10 +36,6 @@ on:
         description: 'REBUILD'
         type: boolean
         default: false
-      INCLUDE_ADMIT:
-        description: 'RUN ADMIT?'
-        type: string
-        default: 'true'
       RETAIN_ENV:
         description: 'RETAIN THE ENVIRONMENT?'
         type: boolean
@@ -78,27 +74,26 @@ jobs:
       UBUNTU_ASAN_TAR_PATH: ${{ steps.param.outputs.UBUNTU_ASAN_TAR_PATH }}
       RETAIN_ENV: ${{ steps.param.outputs.RETAIN_ENV }}
       ALL_LINUX: ${{ steps.param.outputs.ALL_LINUX }}
-      INCLUDE_ADMIT: ${{ steps.param.outputs.INCLUDE_ADMIT }}
     steps:
       - name: CRON PARAM
         id: param
         run: |
           if [[ "${{ github.event_name }}" == "schedule" ]]; then
-            if [[ "${{ github.event.schedule }}" == "0 11 * * 1-5" ]]; then
+            if [[ "${{ github.event.schedule }}" == "0 10 * * 1-5" ]]; then
               branch=branch-3.2
-              [[ "$GITHUB_REPOSITORY" == 'StarRocks/starrocks' ]] && all_linux=true
+              all_linux=true
             elif [[ "${{ github.event.schedule }}" == "30 0 * * 1-5" ]]; then
               branch=main
               all_linux=true
             else
               branch=main
+              all_linux=false
             fi
             base_sha=$(gh api /repos/${REPO}/branches/${branch} | jq -r .commit.sha)
             [[ "${base_sha}" == "null" ]] && (echo "::error::Get HEAD SHA error, please check." && exit -1);
             echo "BRANCH=${branch}" >> $GITHUB_OUTPUT
             echo "PR_NUMBER=${base_sha}" >> $GITHUB_OUTPUT
             echo "ALL_LINUX=${all_linux}" >> $GITHUB_OUTPUT
-            echo "INCLUDE_ADMIT=true" >> $GITHUB_OUTPUT
           else
             echo "BRANCH=${{ inputs.BRANCH }}" >> $GITHUB_OUTPUT
             echo "PR_NUMBER=${{ inputs.COMMIT_ID }}" >> $GITHUB_OUTPUT
@@ -108,7 +103,6 @@ jobs:
             echo "UBUNTU_ASAN_TAR_PATH=${{ inputs.UBUNTU_ASAN_TAR_PATH }}" >> $GITHUB_OUTPUT
             echo "RETAIN_ENV=${{ inputs.RETAIN_ENV }}" >> $GITHUB_OUTPUT
             echo "ALL_LINUX=true" >> $GITHUB_OUTPUT
-            echo "INCLUDE_ADMIT=false" >> $GITHUB_OUTPUT
           fi
 
   be-ut:
@@ -264,7 +258,6 @@ jobs:
     env:
       BRANCH: ${{ needs.info.outputs.BRANCH }}
       PR_NUMBER: ${{ needs.info.outputs.PR_NUMBER }}
-      ALL_LINUX: ${{ needs.info.outputs.ALL_LINUX }}
     steps:
       - name: CLEAN
         run: |
@@ -274,7 +267,6 @@ jobs:
         id: run_build
         shell: bash
         timeout-minutes: 90
-        if: (matrix.build_type == 'Release' && matrix.linux == 'centos7') || env.ALL_LINUX == 'true'
         run: |
           rm -rf ./ci-tool && cp -rf /var/lib/ci-tool ./ci-tool && cd ci-tool && git pull && source lib/init.sh
           ./bin/elastic-build.sh --repository ${{ github.repository }} --branch ${BRANCH} --pr ${PR_NUMBER} --build ${{ matrix.build_type }} --linuxdistro ${{ matrix.linux }}
@@ -312,8 +304,6 @@ jobs:
       - info
       - build
     if: always() && needs.info.result == 'success'
-    env:
-      ALL_LINUX: needs.info.outputs.ALL_LINUX
     outputs:
       RELEASE_TAR_PATH: ${{ steps.set_output.outputs.CENTOS_RELEASE_TAR_PATH }}
       ASAN_TAR_PATH: ${{ steps.set_output.outputs.CENTOS_ASAN_TAR_PATH }}
@@ -339,31 +329,31 @@ jobs:
             build_result=$(cat "./outputs/BUILD-RESULT-Release-centos7/tar.txt")
             echo "CENTOS_RELEASE_TAR_PATH=${build_result}" >> $GITHUB_OUTPUT
           else
-            has_failure=true
+            echo "::error::BUILD FAILED (Release & Centos)!"
+            exit 1
           fi
           
           if [[ -e "./outputs/BUILD-RESULT-ASAN-centos7/tar.txt" ]]; then
             build_result=$(cat "./outputs/BUILD-RESULT-ASAN-centos7/tar.txt")
             echo "CENTOS_ASAN_TAR_PATH=${build_result}" >> $GITHUB_OUTPUT
           else
-            has_failure=true
+            echo "::error::BUILD FAILED (ASAN & Centos)!"
+            exit 1
           fi
           
           if [[ -e "./outputs/BUILD-RESULT-Release-ubuntu/tar.txt" ]]; then
             build_result=$(cat "./outputs/BUILD-RESULT-Release-ubuntu/tar.txt")
             echo "UBUNTU_RELEASE_TAR_PATH=${build_result}" >> $GITHUB_OUTPUT
           else
-            has_failure=true
+            echo "::error::BUILD FAILED (Release & Ubuntu)!"
+            exit 1
           fi
           
           if [[ -e "./outputs/BUILD-RESULT-ASAN-ubuntu/tar.txt" ]]; then
             build_result=$(cat "./outputs/BUILD-RESULT-ASAN-ubuntu/tar.txt")
             echo "UBUNTU_ASAN_TAR_PATH=${build_result}" >> $GITHUB_OUTPUT
           else
-            has_failure=true
-          fi
-          
-          if [[ "${has_failure}" == "true" && "${ALL_LINUX}" == "true" ]]; then
+            echo "::error::BUILD FAILED (ASAN & Ubuntu)!"
             exit 1
           fi
 
@@ -398,7 +388,6 @@ jobs:
       BUILD_TYPE: Release
       LINUX_DISTRO: centos7
       IS_SELF_BUILD: ${{ needs.test_filter.outputs.IS_SELF_BUILD }}
-      INCLUDE_ADMIT: ${{ needs.info.outputs.INCLUDE_ADMIT }}
 
   system-test-asan:
     name: 'ASAN/Centos'
@@ -407,7 +396,7 @@ jobs:
       - info
       - test_filter
     secrets: inherit
-    if: always() && needs.test_filter.outputs.ASAN_TAR_PATH != '' && needs.info.outputs.ALL_LINUX == 'true'
+    if: always() && needs.test_filter.outputs.ASAN_TAR_PATH != ''
     with:
       BRANCH: ${{ needs.info.outputs.BRANCH }}
       COMMIT_ID: ${{ needs.info.outputs.PR_NUMBER }}
@@ -415,7 +404,6 @@ jobs:
       BUILD_TYPE: ASAN
       LINUX_DISTRO: centos7
       IS_SELF_BUILD: ${{ needs.test_filter.outputs.IS_SELF_BUILD }}
-      INCLUDE_ADMIT: ${{ needs.info.outputs.INCLUDE_ADMIT }}
 
   system-test-release-ubuntu:
     name: 'Release/Ubuntu'
@@ -432,7 +420,6 @@ jobs:
       BUILD_TYPE: Release
       LINUX_DISTRO: ubuntu
       IS_SELF_BUILD: ${{ needs.test_filter.outputs.IS_SELF_BUILD }}
-      INCLUDE_ADMIT: ${{ needs.info.outputs.INCLUDE_ADMIT }}
 
   system-test-asan-ubuntu:
     name: 'ASAN/Ubuntu'
@@ -449,7 +436,6 @@ jobs:
       BUILD_TYPE: ASAN
       LINUX_DISTRO: ubuntu
       IS_SELF_BUILD: ${{ needs.test_filter.outputs.IS_SELF_BUILD }}
-      INCLUDE_ADMIT: ${{ needs.info.outputs.INCLUDE_ADMIT }}
 
   Teardown:
     runs-on: [self-hosted, normal]
@@ -538,7 +524,7 @@ jobs:
           fi
 
       - name: save unstable cases
-        if: always() && ((github.event_name == 'schedule' && env.BRANCH == 'main') || (github.event_name != 'schedule' && env.BRANCH != 'main'))
+        if: always() && github.event_name == 'schedule' && env.BRANCH == 'main'
         run: |
           cd ci-tool && source lib/init.sh
           ./bin/save_unstable_cases.sh
