[Tool] debug

diff --git a/.github/workflows/label-action.yml b/.github/workflows/label-action.yml
--- a/.github/workflows/label-action.yml
+++ b/.github/workflows/label-action.yml
@@ -4,6 +4,7 @@ on:
   pull_request_target:
     types:
       - labeled
+      - unlabeled
 
 permissions:
   checks: write
@@ -22,7 +23,7 @@ permissions:
 jobs:
   meta-review:
     name: META REVIEW
-    if: github.event.label.name == 'META-REVIEW'
+    if: github.event.label.name == 'META-REVIEW' && github.event.action == 'labeled'
     runs-on: ubuntu-latest
     env:
       PR_NUMBER: ${{ github.event.pull_request.number }}
@@ -38,3 +39,20 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/requested_reviewers" \
             -d "{\"team_reviewers\":[\"${META_TEAM}\"]}" 2>/dev/null
+
+  review-required-check:
+    name: REQUIRED LABEL CHECK
+    runs-on: ubuntu-latest
+    env:
+      PR_NUMBER: ${{ github.event.pull_request.number }}
+      REPO: ${{ github.repository }}
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    steps:
+      - name: check
+        run: |
+          labels=$(gh pr view ${PR_NUMBER} -R ${REPO} --json labels -q '.labels[].name')
+          if [[ "${labels}" =~ "Review required" ]]; then
+            echo "::error::Review required."
+            exit 1
+          fi
