[Tool] Add backport checklist in pr template (backport #37017) (#37023)
Signed-off-by: andyziye <108652123+andyziye@users.noreply.github.com>
Co-authored-by: andyziye <108652123+andyziye@users.noreply.github.com>

diff --git a/.github/workflows/pr-checker.yml b/.github/workflows/pr-checker.yml
--- a/.github/workflows/pr-checker.yml
+++ b/.github/workflows/pr-checker.yml
@@ -28,8 +28,37 @@ permissions:
   statuses: write
 
 jobs:
+
+  sync-checker:
+    runs-on: ubuntu-latest
+    if: >
+      !contains(github.event.pull_request.title, '(sync #') &&
+      !contains(github.event.pull_request.labels.*.name, 'sync') &&
+      (!startsWith(github.head_ref, github.base_ref) || !contains(github.head_ref, '-sync-'))
+    name: SYNC CHECKER
+    steps:
+      - run: echo "Normal PR."
+
+      - name: backport assign
+        if: startsWith(github.head_ref, 'mergify/bp/') && github.event.action == 'opened'
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          PR_NUMBER: ${{ github.event.number }}
+          REPO: ${{ github.repository }}
+        run: |
+          ORI_PR=$(echo "${{ github.event.pull_request.title }}" | grep -oP '\(backport #\K\d+' | tail -n 1)
+          author=$(gh pr view ${ORI_PR} -R ${REPO} --json author -q '.author.login')
+          if [[ ! "${author}" =~ "mergify" ]]; then
+            gh pr edit ${PR_NUMBER} -R ${REPO} --add-assignee ${author}
+          fi
+
   title-check:
     runs-on: ubuntu-latest
+    needs: sync-checker
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      PR_NUMBER: ${{ github.event.number }}
+      REPO: ${{ github.repository }}
     steps:
       - uses: thehanimo/pr-title-checker@v1.3.5
         with:
@@ -37,7 +66,29 @@ jobs:
           pass_on_octokit_error: false
           configuration_path: ".github/pr-title-checker-config.json"
 
-  branch-info-check:
+      - name: update body
+        if: always() && github.base_ref != 'main' && github.event.action == 'opened'
+        env:
+          GH_TOKEN: ${{ secrets.PAT }}
+        run: |
+          gh pr view ${PR_NUMBER} -R ${REPO} --json body -q .body > body.txt
+          ori_body=$(cat body.txt)
+          sed -i "s#\[ \] This is a backport pr#\[x\] This is a backport pr#g" body.txt
+          if [[ "${ori_body}" != $(cat body.txt) ]]; then
+            gh pr edit ${PR_NUMBER} -R ${REPO} -F body.txt
+          fi
+
+      - name: check backport pr's title
+        if: github.base_ref != 'main' && contains(toJson(github.event.pull_request.body), '[x] This is a backport pr')
+        run: |
+          PR_TITLE=$(echo "${{ github.event.pull_request.title }}")
+          count=$(echo $PR_TITLE | grep -E '\(backport #[0-9]+)$' | wc -l)
+          if [[ $count -le 0 ]]; then
+            echo "::error::Backport PR title is not valid. It should end with '(backport #[0-9]+)'"
+            exit 1
+          fi
+
+  backport-check:
     needs: title-check
     runs-on: ubuntu-latest
     if: >
@@ -108,13 +159,18 @@ jobs:
 
   automerge-check:
     runs-on: ubuntu-latest
-    needs: branch-info-check
-    if: ${{ !failure() && (contains(github.event.pull_request.title, 'cherry-pick') || contains(github.event.pull_request.title, 'backport')) }}
+    needs: backport-check
+    if: >
+      !failure() &&
+      github.base_ref != 'main' &&
+      startsWith(github.head_ref, 'mergify/') &&
+      (contains(github.event.pull_request.title, 'cherry-pick') || 
+      contains(github.event.pull_request.title, 'backport'))
     steps:
       - name: add automerge label
         uses: actions-ecosystem/action-add-labels@v1
         with:
-          github_token: ${{ secrets.PAT }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
           labels: automerge
 
       - name: automerge
