test
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>

diff --git a/.github/workflows/pr-checker.yml b/.github/workflows/pr-checker.yml
--- a/.github/workflows/pr-checker.yml
+++ b/.github/workflows/pr-checker.yml
@@ -63,6 +63,21 @@ jobs:
         run: |
           echo "::error::Please check the format of your pr body about the behavior change checkbox!"
           exit 1
-          
+
+      - name: Format Check4
+        id: check4
+        if: >
+          contains(github.event.pull_request.body, '[ ] Yes, this PR will result in a change in behavior')
+        run: |
+          echo "::error::Please check the format of your pr body about the behavior change checkbox!"
+          exit 1
+
+      - name: Format Check5
+        id: check5
+        if: >
+          contains(github.event.pull_request.body, ' Yes, this PR will result in a change in behavior')
+        run: |
+          echo "::error::Please check the format of your pr body about the behavior change checkbox!"
+          exit 1
       
 
