[Tool] add retry for sync workflow (#43654)

diff --git a/.github/workflows/repo-sync.yml b/.github/workflows/repo-sync.yml
--- a/.github/workflows/repo-sync.yml
+++ b/.github/workflows/repo-sync.yml
@@ -317,10 +317,32 @@ jobs:
           BODY_FILE: /var/local/env/body/${{ github.repository }}/${{ inputs.PR_ID }}.txt
           REVIEWER: ${{ needs.pr-info.outputs.assignees }}
         run: |
-          info=`gh pr create -B ${{ inputs.BRANCH }} -H "${HEAD}" -l "${PR_LABEL}" -t "${TITLE}" -F "${BODY_FILE}" -r "${REVIEWER}"`
-          echo $info
+          if [[ ! -e ${BODY_FILE} ]]; then
+            echo "File ${BODY_FILE} not found"
+            exit 1
+          fi
+
+          for i in {1..3}; do
+            is_succ=true
+            info=`gh pr create -B ${{ inputs.BRANCH }} -H "${HEAD}" -l "${PR_LABEL}" -t "${TITLE}" -F "${BODY_FILE}" -r "${REVIEWER}"` || is_succ=false
+            if [[ "$is_succ" != "false" ]]; then
+              echo $info
+              break
+            else
+              sleep 3
+            fi
+          done
+          
+          # check pr url
+          if [[ "$is_succ" != "true" ]]; then
+            echo "::error::Create pull request failed"
+            exit 1
+          fi
+
           pr_url=`echo $info | tail -n 1`
-          echo pr_url=${pr_url} >> $GITHUB_OUTPUT
+          if [[ -n $pr_url ]]; then
+            echo pr_url=${pr_url} >> $GITHUB_OUTPUT
+          fi
 
       # previous pr files' check pending
       - name: Create pending pull request
